export const SET_EXPENCEDATA = "SET_EXPENCEDATA";
export const UPDATE_EXPENCEDATA = "UPDATE_EXPENCEDATA";
export const DELETE_EXPENCEDATA = "DELETE_EXPENCEDATA";
export const POPUP_EXPENCEDATA = "POPUP_EXPENCEDATA";
export const RESET_EXPENCEDATA = "RESET_EXPENCEDATA";
