export const SET_INCOMEDATA = "SET_INCOMEDATA";
export const UPDATE_INCOMEDATA = "UPDATE_INCOMEDATA";
export const DELETE_INCOMEDATA = "DELETE_INCOMEDATA";
export const RESET_INCOMEDATA = "RESET_INCOMEDATA";

